package lk.ijse.the_car_guys.util;

public enum Routes {
    ADMIN,PANE,STAGE,LOGIN,REC,REC_DASH,REC_CLIENTS,REC_ORDER,L,
    SERVICE,SPARE_PART,WAITING,CUSTOMER,VEHICLE,PAYMENT,VEHICLE_UPDATE,PAYMENT_ORDER,
    USER,USER_ALL,USER_UPDATE,ADMIN_CLIENTS,ADMIN_CLIENTS_ADD,ADMIN_CLIENTS_UPD,
    ADMIN_SPARE_PART,ADMIN_SPARE_PART_ALL,ADMIN_SPARE_PART_UPD,LOGIN_DETAILS,
    ADMIN_SERVICE,ADMIN_SERVICE_UPD,ADMIN_VEHICLE,ADMIN_VEHICLE_UPD,REC_REPAIR,
    PAYMENT_REPAIR,REPORT;
}
