package lk.ijse.the_car_guys.dao;

public enum DaoTypes {
    USER,CUSTOMER,VEHICLE,WAITING_LIST,ORDER,ORDER_DETAIL,SPARE_PART,LOGIN_DETAILS,PAYMENT_ORDER,
    PAYMENT_REPAIR,REPAIR,R_SERVICE_DETAILS,SERVICE
}
